"""HM parameter-estimation test: inject SEOBNRv4HM, recover with surrogate vs pycbc.

Events with strong higher modes (GW190412/GW190814) have secondary masses below
the 20-100 Msun training range, so this tests HM PE on an in-domain high-mass-ratio
injection instead. A true SEOBNRv4HM signal (generated by pycbc) is injected into
aLIGO-coloured noise; the surrogate and live pycbc are each used as the template
engine through the identical estimator, prior and warm start -- so any difference
is the surrogate. Inclination is a free parameter (higher modes are what make it
measurable), alongside the two masses and two aligned spins.

Usage:
    python scripts/hm_pe_inject.py --surrogate checkpoints/seobnrv4hm_5mode_20k \
        --m1 85 --m2 24 --s1z 0.4 --s2z -0.1 --inc 1.1 --snr 30 \
        --nwalkers 30 --nsteps 800 --outdir docs/images/hm_pe_inject
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.data.generator import WaveformGenerator  # noqa: E402
from src.inference.estimator import GWEventEstimator, Prior, WaveformBank  # noqa: E402
from src.inference.gwosc import DetectorData, EventData  # noqa: E402
from src.inference.predictor import WaveformPrediction  # noqa: E402
from src.inference.surrogate import load_surrogate  # noqa: E402


class PyCBCEngine:
    """WaveformPredictor-compatible engine emitting live pycbc fixed-window templates."""

    def __init__(self, approximant, L, delta_t, f_lower=20.0, merger_frac=0.9):
        self.delta_t = delta_t
        self.meta = {"td_fixed_window": True, "merger_frac": merger_frac}
        self.reduced_order = True
        self._g = WaveformGenerator(waveform_length=L, delta_t=delta_t, f_lower=f_lower,
                                    approximant=approximant, fixed_window=True)

    def predict(self, m1, m2, s1z=0.0, s2z=0.0, inc=0.0, ecc=0.0, sigma_level=None):
        h = self._g._generate_single_waveform(np.array([m1, m2, s1z, s2z, inc, ecc]), clean=True)
        return WaveformPrediction(np.asarray(h, float), sample_rate=self.delta_t), \
            WaveformPrediction(np.zeros_like(h), sample_rate=self.delta_t)

    def batch_predict(self, full, batch_size=256):
        hp = [self.predict(*p)[0] for p in np.asarray(full)]
        return hp, [WaveformPrediction(np.zeros_like(w.data), sample_rate=self.delta_t) for w in hp]


def build_injection(m1, m2, s1z, s2z, inc, coa_phase, snr_target, sample_rate, duration,
                    f_lower, seed):
    """Return an EventData: a SEOBNRv4HM injection in aLIGO-coloured noise (1 detector)."""
    from pycbc.waveform import get_td_waveform
    from pycbc.types import TimeSeries
    from pycbc.psd import aLIGOZeroDetHighPower, interpolate, inverse_spectrum_truncation
    from pycbc.noise import noise_from_psd
    from pycbc.filter import sigma

    dt = 1.0 / sample_rate
    N = int(duration * sample_rate)
    gps = 1234567890.0

    hp, _ = get_td_waveform(approximant="SEOBNRv4HM", mass1=m1, mass2=m2, spin1z=s1z, spin2z=s2z,
                            inclination=inc, coa_phase=coa_phase, distance=1.0,
                            delta_t=dt, f_lower=f_lower)
    hp = np.asarray(hp, dtype=float)
    # place the merger (peak) at the segment centre
    pk = int(np.abs(hp).argmax())
    sig = np.zeros(N)
    c = N // 2
    lo = c - pk
    seg = hp[max(0, -lo):]
    lo = max(0, lo)
    seg = seg[:N - lo]
    sig[lo:lo + len(seg)] = seg

    # PSD + noise
    flen = N // 2 + 1
    df = 1.0 / duration
    psd = aLIGOZeroDetHighPower(flen, df, f_lower)
    rng = np.random.default_rng(seed)
    noise = np.asarray(noise_from_psd(N, dt, psd, seed=int(rng.integers(1 << 31))), dtype=float)

    # scale the signal to the target optimal SNR under this PSD
    sig_ts = TimeSeries(sig, delta_t=dt)
    ss = sigma(sig_ts, psd=psd, low_frequency_cutoff=f_lower)
    sig *= (snr_target / float(ss))
    inj_scale = snr_target / float(ss)

    strain = TimeSeries(sig + noise, delta_t=dt, epoch=gps - duration / 2)
    seg_len = int(4 * sample_rate)
    psd_ist = inverse_spectrum_truncation(psd, seg_len, low_frequency_cutoff=f_lower,
                                          trunc_method="hann")
    det = DetectorData(detector="H1", strain=strain, psd=psd_ist, delta_t=dt,
                       epoch=float(strain.start_time))
    ev = EventData(event_name="INJ_HM", gps_time=gps, detectors={"H1": det}, f_lower=f_lower)
    return ev, inj_scale


def summarise(res):
    out = {}
    s = res.samples
    for i, n in enumerate(res.param_names):
        lo, hi = np.percentile(s[:, i], [5, 95])
        out[n] = [float(np.median(s[:, i])), float(lo), float(hi)]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--surrogate", required=True)
    ap.add_argument("--m1", type=float, default=85.0)
    ap.add_argument("--m2", type=float, default=24.0)
    ap.add_argument("--s1z", type=float, default=0.4)
    ap.add_argument("--s2z", type=float, default=-0.1)
    ap.add_argument("--inc", type=float, default=1.1)
    ap.add_argument("--coa-phase", type=float, default=0.3)
    ap.add_argument("--snr", type=float, default=30.0)
    ap.add_argument("--sample-rate", type=float, default=4096.0)
    ap.add_argument("--duration", type=float, default=32.0)
    ap.add_argument("--nwalkers", type=int, default=30)
    ap.add_argument("--nsteps", type=int, default=800)
    ap.add_argument("--bank-size", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    truth = dict(m1=args.m1, m2=args.m2, s1z=args.s1z, s2z=args.s2z, inc=args.inc)

    surrogate = load_surrogate(args.surrogate, device=args.device)
    L = surrogate.L
    pycbc_engine = PyCBCEngine("SEOBNRv4HM", L, surrogate.delta_t, f_lower=surrogate.f_lower,
                               merger_frac=surrogate.merger_frac)

    ev, _ = build_injection(args.m1, args.m2, args.s1z, args.s2z, args.inc, args.coa_phase,
                            args.snr, args.sample_rate, args.duration, surrogate.f_lower, args.seed)

    # free masses + aligned spins + inclination; ecc fixed 0
    prior = Prior(bounds={"m1": (20.0, 100.0), "m2": (20.0, 100.0),
                          "s1z": (-0.9, 0.9), "s2z": (-0.9, 0.9),
                          "inc": (0.0, np.pi)}, fixed={"ecc": 0.0})

    out = {"truth": truth, "snr": args.snr}
    p0 = None
    for tag, eng in (("surrogate", surrogate), ("pycbc", pycbc_engine)):
        est = GWEventEstimator(eng, ev, prior=prior, likelihood="matched_filter")
        if p0 is None:
            bank = WaveformBank(surrogate, prior=prior)
            bank.build(n_samples=args.bank_size, seed=args.seed)
            p0 = est.initialize_walkers(args.nwalkers, bank=bank, seed=args.seed)
        t0 = time.time()
        res = est.run_mcmc(nwalkers=args.nwalkers, nsteps=args.nsteps, p0=p0.copy(),
                           progress=False, seed=args.seed)
        dt = time.time() - t0
        out[tag] = {"seconds": round(dt, 1), "acceptance": round(float(res.acceptance_fraction), 3),
                    "summary": summarise(res)}
        out[f"_res_{tag}"] = res
        sm = out[tag]["summary"]
        print(f"{tag:9s} {dt:6.1f}s acc={res.acceptance_fraction:.2f}  "
              f"m1={sm['m1'][0]:.1f} m2={sm['m2'][0]:.1f} s1z={sm['s1z'][0]:+.2f} "
              f"inc={sm['inc'][0]:.2f}", flush=True)

    # corner overlay
    try:
        import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt; import corner
        rs, rp = out.pop("_res_surrogate"), out.pop("_res_pycbc")
        labels = rs.param_names
        truths = [truth.get(n) for n in labels]
        rng = [(min(a.min(), b.min()), max(a.max(), b.max())) for a, b in zip(rs.samples.T, rp.samples.T)]
        fig = corner.corner(rp.samples, labels=labels, color="C1", range=rng, truths=truths,
                            truth_color="k", hist_kwargs={"density": True})
        corner.corner(rs.samples, fig=fig, labels=labels, color="C0", range=rng,
                      hist_kwargs={"density": True})
        fig.suptitle("HM injection: surrogate (blue) vs pycbc (orange), truth (black)", y=1.02)
        fig.savefig(os.path.join(args.outdir, "corner_hm_inject.png"), dpi=150, bbox_inches="tight")
    except Exception as exc:  # noqa: BLE001
        print("corner failed:", exc)
        out.pop("_res_surrogate", None); out.pop("_res_pycbc", None)

    json.dump(out, open(os.path.join(args.outdir, "hm_pe_inject.json"), "w"), indent=2)
    print(json.dumps({k: v for k, v in out.items() if not k.startswith("_")}, indent=2))


if __name__ == "__main__":
    main()
